export const songList = {
  byUk: [
    "Океан Эльзы – на небi",
    "Океан Эльзы – Я так хочу",
    "Океан Эльзы – без бою",
    "N.R.M. - паветраны шар",
    "N.R.M. - тры чарапаxi",
  ],
  ru: [
    "Агата Кристи  –  как на войне",
    "Агата Кристи  –  сказочная тайга",
    "Ария - беспечный ангел",
    "Антонов - мечты",
    "Антонов - летящей походкой",
    "Айова - улыбайся",
    "Браво – Любите девушки",
    "Браво – Московский бит",
    "Гарик Сукачев – Моя бабушка",
    "Гребенщиков - мечи стаканы на стол",
    "Григорий Лепс –  рюмка водки на столе",
    "Жуки – батарейка",
    "Жуки - танкист",
    "Звери – районы-кварталы",
    "Звери - касается",
    "Земляне – трава у дома",
    "Кино –  группа крови",
    "Кино – видели ночь (Zdob Si Zdub vers.)",
    "Кино - звезда",
    "Кино - кукушка",
    "Кино - пачка сигарет",
    "КИШ - ели мясо мужики",
    "КИШ - лесник",
    "Ленинград – WWW",
    "Ленинград – мамба",
    "Ленинград – рыба",
    "Леприконсы –  хали-гали",
    "Леприконсы –  снегурочка",
    "Ляпис Трубецкой – ау",
    "Ляпис Трубецкой – грай",
    "Ляпис Трубецкой - Воины света",
    "Ляпис Трубецкой - Зорачки",
    "Ляпис Трубецкой – капитал",
    "Машина Времени - за тех кто в море",
    "Машина Времени – поворот",
    "Михаил Боярский – зеленоглазое такси",
    "Мумий Тролль - Владивосток 2000",
    "Мумий Тролль - Медведица",
    "Найк Борзов - верхом на звезде",
    "Найк Борзов - лошадка",
    "Ногу свело - лилипутская любовь",
    "Сплин - лама",
    "Сплин - выхода нет",
    "Сплин - орбит",
    "Сплин –  мое сердце",
    "Чайф - в ее глазах",
    "Чайф - не спеши",
    "Чайф – никто не услышит(Ой-йо)",
    "Чайф – пусть всё будет так, как ты захочешь",
    "Чиж - фантом",
  ],
  eng: [
    "AC/DC –highway to hell",
    "AC/DC - thunderstruck",
    "AC/DC - You Shook Me All Night Long",
    "Audioslave - be yourself",
    "Alice Merton - No Roots",
    "Beatles - Back In The USSR",
    "Beatles - come together",
    "Billie Eilish - bad guy",
    "Blur – song 2",
    "Bon Jovi – It's my life",
    "Britney Spirs – I like Rock n Roll",
    "Cranberries -  Zombie",
    "Creedence Clearwater Revival - have you ever seen the rain",
    "Coldplay - adventure of a lifetime",
    "Coldplay - charlie brown ",
    "Chuck Berry - Johnny B. Goode",
    "Chuck Berry  - you never can tell ",
    "Chubby Checker - let's twist again",
    "Daft Punluckyk - Get ",
    "DNCE – kissing stranger",
    "Deep Purple – smoke on the water",
    "Depeche mode - enjoy the silence",
    "Depeche Mode –  personal Jesus",
    "Dick Dale – misirlou ",
    "Eagles - Hotel California",
    "Ed Sheeran - shape of you",
    "Elvis Presley – blue Suede Shoes",
    "Gary Moore - Still got the Blues",
    "George Harrison - got my mind set on you",
    "Guns N`Roses – knockin' On Heaven's Door",
    "James Brown - I feel good",
    "Justin Timberlake - Can't stop the feeling",
    "Joan Osborne - one of us",
    "Katy Perry - Hot n Cold",
    "Linkin Park - Crowling",
    "Mr.Big - Wild World",
    "Nickelback - How You Remind Me",
    "Nirvana – rape Me",
    "Nirvana – smels Like Teen Spirit",
    "Metallica - enter sandman",
    "Metallica - enter nothing else matters",
    "Ozzy Ozborn - Mama i'm coming home",
    "Pink Floyd  – another Brick In The Wall",
    "Queen - We are the champions",
    "Queen - little thing called love",
    "Ray Parker Jr. - Ghostbusters",
    "Radiohead – creep",
    "The Rasmus - In the Shadows",
    "Red Hot Chili Peppers - californication",
    "REM -lusing my religion",
    "Ricky Martin - livin la vida loca",
    "Robie Williams - Feel",
    "Roy Orbison – pretty women",
    "Scorpions - wind of change",
    "Smokie - Alice",
    "Shocking Blue – venus",
    "SRV – mary head a little lamb",
    "Sting - englishman",
    "Sting - every breath you take",
    "Sting - shape of my heart",
    "the subways - rock n roll queen",
    "Zucchero - Baila morena",
  ],
};
