export const ACTIONS = {
  GET_DATA_USERS_COST: "GET_DATA_USERS_COST",
  GET_DATA_DB_COST: "GET_DATA_DB_COST",
  PAYMENT_BAND_COST: "PAYMENT_BAND_COST",
  SET_BAND_COST: "SET_BAND_COST",
  CHANGE_WAS_PAYMENT: "CHANGE_WAS_PAYMENT",
  GET_POSTERS_DB_SUCCES: "GET_POSTERS_DB_SUCCES",
  GET_POSTERS_DB: "GET_POSTERS_DB",
  PUSH_POSTER: "PUSH_POSTER",
  REMOVE_POSTER: "REMOVE_POSTER",
  CHECK_LOGIN_PASSWORD_ADMIN: "CHECK_LOGIN_PASSWORD_ADMIN",
};
