export const ACTIONS = {
  GET_DATA_USERS_COST: "GET_DATA_USERS_COST",
  GET_DATA_DB_COST: "GET_DATA_DB_COST",
  PAYMENT_BAND_COST: "PAYMENT_BAND_COST",
  SET_BAND_COST: "SET_BAND_COST",
  CHANGE_WAS_PAYMENT: "CHANGE_WAS_PAYMENT",
};
